### ISSUE TITLE
can't download

### ISSUE THREAD

**Issue by a456pur** [tommiecc/ScrolllerDownloader#1]
i can't download because i don't have enough storage on my iphone. this error doesn't seem to be anywhere in the github documentation. any ideas on how to fix this.

platform:
operating system / iOS 11.4
browser / safari

**Comment by tommiecc** [comment]
ScrolllerDownload doesn't work with mobile.

**Comment by tommiecc** [comment]
ScrolllerDownload doesn't work with mobile devices.

**Comment by a456pur** [comment]
aw shucks
